### ISSUE TITLE
Contact me

### ISSUE THREAD

**Issue by mercenaruss** [Tarik2142/devHost#1]
Hi, please contact me using Telegram : https://t.me/mercenaruss
Best Regards

**Comment by Tarik2142** [comment]
Hi, @mercenaruss 
This is a very strange issue, it looks like a scam.
I created this repository for my tests, I have no idea what problems other people might have with it

**Comment by mercenaruss** [comment]
> Hi, @mercenaruss 
> 
> This is a very strange issue, it looks like a scam.
> 
> I created this repository for my tests, I have no idea what problems other people might have with it

@Tarik2142 Sorry maybe i didnt introduce myself. I didnt know how to contact you other way. 
I'm working on ZigStar [www.zig-star.com](www.zig-star.com) projects and i need your assistance/consultation with 
https://github.com/smlight-dev/slzb-06-firmware

**Comment by Tarik2142** [comment]
> > Hi, @mercenaruss
> > This is a very strange issue, it looks like a scam.
> > I created this repository for my tests, I have no idea what problems other people might have with it
> 
> @Tarik2142 Sorry maybe i didnt introduce myself. I didnt know how to contact you other way. I'm working on ZigStar [www.zig-star.com](www.zig-star.com) projects and i need your assistance/consultation with https://github.com/smlight-dev/slzb-06-firmware

I do not use my personal TG account for business purposes. If you need direct contact via Telegram, contact https://t.me/smartlightme
If you have any questions about [slzb-06-firmware](https://github.com/smlight-dev/slzb-06-firmware), feel free to open issue and we try to help. We are always open for cooperation.

**Comment by mercenaruss** [comment]
Thank you!

**Comment by Tarik2142** [comment]
Friend, you should not have followed the path of escalation, these actions will have consequences. You can see for yourself that this is 80% unique firmware. Now I will bring the case to the end and in the new release there will be nothing left of your code :)
